dependencies:
- name: common-data
  version: ~20190125-18.26.43
  repository: "file://charts/common-data"
- name: ev-gb-center
  version: ~20190125-18.26.43
  repository: "file://charts/ev-gb-center"
- name: ev-gb-dispatcher
  version: ~20190125-18.26.43
  repository: "file://charts/ev-gb-dispatcher"
- name: ev-gb-gateway
  version: ~20190125-18.26.43
  repository: "file://charts/ev-gb-gateway"
- name: ev-gb-tcu
  version: ~20190125-18.26.43
  repository: "file://charts/ev-gb-tcu"
- name: ev-gb-uploader
  version: ~20190125-18.26.43
  repository: "file://charts/ev-gb-uploader"
- name: evgb-dtc
  version: ~20190125-18.26.43
  repository: "file://charts/evgb-dtc"
- name: evgb-dts
  version: ~20190125-18.26.43
  repository: "file://charts/evgb-dts"
- name: evgb-rus
  version: ~20190125-18.26.43
  repository: "file://charts/evgb-rus"
- name: file-service
  version: ~20190125-18.26.43
  repository: "file://charts/file-service"
- name: global-search-service
  version: ~20190125-18.26.43
  repository: "file://charts/global-search-service"
- name: global-search-stream
  version: ~20190125-18.26.43
  repository: "file://charts/global-search-stream"
- name: global-search-sync
  version: ~20190125-18.26.43
  repository: "file://charts/global-search-sync"
- name: ime-idp
  version: ~20190125-18.26.43
  repository: "file://charts/ime-idp"
- name: location-data-service
  version: ~20190125-18.26.43
  repository: "file://charts/location-data-service"
- name: message-center-service
  version: ~20190125-18.26.43
  repository: "file://charts/message-center-service"
- name: message-center-service-2
  version: ~20190125-18.26.43
  repository: "file://charts/message-center-service-2"
- name: message-push-service
  version: ~20190125-18.26.43
  repository: "file://charts/message-push-service"
- name: message-push-service-2
  version: ~20190125-18.26.43
  repository: "file://charts/message-push-service-2"
- name: ne-config-server
  version: ~20190125-18.26.43
  repository: "file://charts/ne-config-server"
- name: ne-eureka-server
  version: ~20190125-18.26.43
  repository: "file://charts/ne-eureka-server"
- name: ne-evgb-dashboard
  version: ~20190125-18.26.43
  repository: "file://charts/ne-evgb-dashboard"
- name: ne-evgb-nservice
  version: ~20190125-18.26.43
  repository: "file://charts/ne-evgb-nservice"
- name: ne-external-gateway
  version: ~20190125-18.26.43
  repository: "file://charts/ne-external-gateway"
- name: ne-icev3-dashboard
  version: ~20190125-18.26.43
  repository: "file://charts/ne-icev3-dashboard"
- name: ne-icev3-h5
  version: ~20190125-18.26.43
  repository: "file://charts/ne-icev3-h5"
- name: ne-icev3-nservice
  version: ~20190125-18.26.43
  repository: "file://charts/ne-icev3-nservice"
- name: ne-icev3-nservice-sub
  version: ~20190125-18.26.43
  repository: "file://charts/ne-icev3-nservice-sub"
- name: ne-inside-gateway
  version: ~20190125-18.26.43
  repository: "file://charts/ne-inside-gateway"
- name: remote-service
  version: ~20190125-18.26.43
  repository: "file://charts/remote-service"
- name: simu-ve
  version: ~20190125-18.26.43
  repository: "file://charts/simu-ve"
- name: user-core-data
  version: ~20190125-18.26.43
  repository: "file://charts/user-core-data"
- name: vehicle-alert-service
  version: ~20190125-18.26.43
  repository: "file://charts/vehicle-alert-service"
- name: vehicle-core-data
  version: ~20190125-18.26.43
  repository: "file://charts/vehicle-core-data"
- name: vehicle-status-service
  version: ~20190125-18.26.43
  repository: "file://charts/vehicle-status-service"
- name: infra-middleware
  version: ~0.9.1
  repository: "file://charts/infra-middleware"
