apiVersion: v1
kind: Service
metadata:
  labels:
    app: pinpoint-mysql
  name: pinpoint-mysql
spec:
  ports:
  - name: tcp-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: pinpoint-mysql
  type: ClusterIP