{{ if and .Values.xxxxxx.ingress.internal .Values.xxxxxx.service.ports }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    description: auto
    {{ if .Values.global.ingress.internal.annotations.kubernetes.io.ingress.class }}
    kubernetes.io/ingress.class: {{ .Values.global.ingress.internal.annotations.kubernetes.io.ingress.class }}
    {{ else }}
    kubernetes.io/ingress.class: kong-ingress-internal
    {{- end }}
  labels:
    qcloud-app: {{ template "xxxxxx.name" . }}
  name: {{ template "xxxxxx.name" . }}-internal
spec:
  rules:
  {{- if .Values.xxxxxx.service.ports }}
  {{- range $port := .Values.xxxxxx.service.ports }}
  - host: port-{{ $port }}-{{ template "xxxxxx.name" . }}-{{ .Release.Namespace }}.{{ .Values.xxxxxx.ingress.internal.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ template "xxxxxx.name" . }}
          servicePort: {{ $port }}
        path: /
  {{- end}}
  {{- end}}
{{ end }}
