apiVersion: v1
kind: Service
metadata:
  name: {{ template "xxxxxx.fullname" . }}
  labels:
    app: {{ template "xxxxxx.name" . }}
    chart: {{ template "xxxxxx.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- with .Values.xxxxxx.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{ if .Values.xxxxxx.service.type }}
  type: {{ .Values.service.type }}
  {{ else }}
  type: ClusterIP
  {{- end }}
  ports:
  {{- range $port := .Values.xxxxxx.service.ports }}
  - name: {{ $port }}-tcp
    port: {{ $port }}
    targetPort: {{ $port }}
    protocol: TCP
  {{- end}}
  selector:
    app: {{ template "xxxxxx.name" . }}
  sessionAffinity: None
