zorg:
  _pathenv:
    dev_ingress_class_internal: nginx
    dev_ingress_class_public: nginx
    dev_ingress_internal_enabled: true
    dev_ingress_public_enabled: true
    dev_k8s_ns_suffix: -dev
    dev_kubeconfig: /root/.kube/config
    docker_ns: default
    docker_repo: docker.io
    ingress_class_internal: nginx
    ingress_class_public: nginx
    k8s_ns: ""
    prd_ingress_class_internal: nginx
    prd_ingress_class_public: nginx
    prd_ingress_internal_enabled: true
    prd_ingress_public_enabled: false
    prd_k8s_ns_suffix: -prd
    prd_kubeconfig: /root/.kube/config
    test_ingress_class_internal: nginx
    test_ingress_class_public: nginx
    test_ingress_internal_enabled: true
    test_ingress_public_enabled: true
    test_k8s_ns_suffix: -test
    test_kubeconfig: /root/.kube/config
    uat_ingress_class_internal: nginx
    uat_ingress_class_public: nginx
    uat_ingress_internal_enabled: true
    uat_ingress_public_enabled: true
    uat_k8s_ns_suffix: -uat
    uat_kubeconfig: /root/.kube/config