bu5:
  _pathenv:
    JIRA_SERVER_URL: https://jira.nx-code.com
    JIRA_PROJECT_ID: BU5
    DOCKER_REPO: harbor.nx-engine.com
    DOCKER_NS: bu5
    INGRESS_CLASS_INTERNAL:
    INGRESS_CLASS_PUBLIC:
    K8S_NS:
    K8S_DOMAIN_INTERNAL:
    K8S_DOMAIN_PUBLIC:
    DEV_K8S_KUBECONFIG: /root/.kube/bu5-idc-dev.config
    DEV_K8S_NS_SUFFIX: "-dev"
    DEV_INGRESS_CLASS_INTERNAL: nginx
    DEV_INGRESS_CLASS_PUBLIC: nginx
    DEV_INGRESS_INTERNAL_ENABLED: true
    DEV_INGRESS_PUBLIC_ENABLED: true
    DEV_K8S_DOMAIN_PUBLIC: cd-dev.nxengine.com
    DEV_K8S_DOMAIN_INTERNAL: bu5-dev.cd
    TEST_K8S_NS_SUFFIX: "-test"
    TEST_K8S_KUBECONFIG: /root/.kube/bu5-idc-dev.config
    TEST_INGRESS_CLASS_INTERNAL: nginx
    TEST_INGRESS_CLASS_PUBLIC: nginx
    TEST_INGRESS_INTERNAL_ENABLED: true
    TEST_INGRESS_PUBLIC_ENABLED: true
    TEST_K8S_DOMAIN_PUBLIC: cd-dev.nxengine.com
    TEST_K8S_DOMAIN_INTERNAL: bu5-dev.cd
    TEST_NOTICE_EMAIL:
    UAT_K8S_NS_SUFFIX: "-uat"
    UAT_K8S_KUBECONFIG: /root/.kube/bu5-idc-test.config
    UAT_INGRESS_CLASS_INTERNAL: nginx
    UAT_INGRESS_CLASS_PUBLIC: nginx
    UAT_INGRESS_INTERNAL_ENABLED: true
    UAT_INGRESS_PUBLIC_ENABLED: true
    UAT_K8S_DOMAIN_PUBLIC: nxengine.cn
    UAT_K8S_DOMAIN_INTERNAL: bu5-test.cd
    UAT_NOTICE_EMAIL:
    PRD_K8S_NS_SUFFIX: "-prd"
    PRD_K8S_KUBECONFIG: /root/.kube/bu5-idc-test.config
    PRD_INGRESS_CLASS_INTERNAL: nginx
    PRD_INGRESS_CLASS_PUBLIC: nginx
    PRD_INGRESS_INTERNAL_ENABLED: true
    PRD_INGRESS_PUBLIC_ENABLED: false
    PRD_K8S_DOMAIN_PUBLIC: nxengine.cn
    PRD_K8S_DOMAIN_INTERNAL: bu5-test.cd
    PRD_NOTICE_EMAIL:
  paas:
    _pathenv:
      JIRA_PROJECT_ID: TDP
      TEST_K8S_KUBECONFIG: /root/.kube/config
      UAT_K8S_KUBECONFIG: /root/.kube/config
      PRD_K8S_KUBECONFIG: /root/.kube/config
  ice-v3:
    _pathenv:
      JIRA_PROJECT_ID: ICEV3
      TEST_K8S_KUBECONFIG: /root/.kube/bu5-idc-test.config
      UAT_K8S_KUBECONFIG: /root/.kube/bu5-idc-test.config
      PRD_K8S_KUBECONFIG: /root/.kube/bu5-idc-test.config
  nx-cloud:
    _pathenv:
      TEST_K8S_KUBECONFIG: /root/.kube/bu5-idc-test.config
      UAT_K8S_KUBECONFIG: /root/.kube/bu5-idc-test.config
      PRD_K8S_KUBECONFIG: /root/.kube/bu5-idc-test.config
  nx-cloud-eco:
    _pathenv:
      TEST_K8S_KUBECONFIG: /root/.kube/bu5-tx-test.config
      TEST_K8S_NS: nx-cloud-eco-test
      TEST_INGRESS_CLASS_INTERNAL: nginx
      TEST_INGRESS_CLASS_PUBLIC: nginx
      TEST_K8S_DOMAIN_INTERNAL: bu5-test.tx
      TEST_K8S_DOMAIN_PUBLIC: bu5-test.nxengine.com
      TEST_INGRESS_PUBLIC_ENABLED: false
  saleen:
    _pathenv:
      JIRA_PROJECT_ID: TDP
      TEST_K8S_KUBECONFIG: /root/.kube/bu5-tx-test.config
      TEST_K8S_NS: saleen-test
      TEST_INGRESS_CLASS_INTERNAL: nginx
      TEST_INGRESS_CLASS_PUBLIC: nginx
      TEST_K8S_DOMAIN_INTERNAL: bu5-test.tx
      TEST_K8S_DOMAIN_PUBLIC: bu5-test.nxengine.com
      TEST_INGRESS_PUBLIC_ENABLED: false