apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr
  labels:
    app.kubernetes.io/name: solr
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: solr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: solr
    spec:
      containers:
      - name: solr
        image: solr:7-alpine
        securityContext:
          readOnlyRootFilesystem: true
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - '/opt/solr/bin/solr status'
        ports:
        - name: solr
          containerPort: 8983
        volumeMounts:
        - name: cores
          mountPath: /opt/solr/server/solr/mycores
        - name: logs
          mountPath: /opt/solr/server/logs
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: cores
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: solr
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: logs
        emptyDir: {}
      - name: tmp
        emptyDir:
          medium: Memory
