#s2i:1
stages:
  - s2i
s2i:
  stage: s2i
  script:
    - export DOCKER_PASS}="fakepass"
    - make docker-centos-pre
  except:
    - tags
  artifacts:
    when: on_success
    expire_in: 24h
    paths:
      - .dist/
#####
