#s2i:2

stages:
  - code-check
#  - artifact-docker-build
#  - deploy-env
#  - artifact-release
#  - src-release
#####
stages:
  - code-check
code-check:
  stage: code-check
  script:
    - gitlab-ci-check
  except:
    - tags