#s2i:2

stages:
  - artifact-docker-build
  - deploy-env
  - artifact-release
  - src-release
#####
stages:
  - analysis-code
code-analysis:
  stage: analysis-code
  script:
     - gitlab-ci-check
  except:
    - tags
#####
stages:
  - src-release
src-mr-create:
  stage: src-release
  when: manual
  script:
     - gitlab-mr-create
  except:
    - master
    - /^hotfix.*$/
    - tags
stages:
  - src-release
gitlab-auto-merge:
  stage: src-release
  script:
     - gitlab-auto-merge
  only:
    - /^hotfix.*$/
  except:
    - tags
#####

stages:
  - artifact-release
artifact-release-job:
  stage: artifact-release
  when: manual
  script:
    - export IMG="$(head -n 1 .s2i/s2i.*img.txt)"
    - echo ${IMG}
    - perl -ni -e "s@${DOCKER_REPO}.+@${IMG}@g;print" runner/docker-compose.yaml
  except:
    - tags
    - master
  artifacts:
    when: on_success
    name: ${CI_PROJECT_NAME}-${CI_JOB_STAGE}
    expire_in: 24h
    paths:
      - runner/