stages:
  - rc
rc:
  stage: rc
  script:
     - env
     - chmod +x *
     - rm -rf output;mkdir -p output
     - ./rc-nacos.sh
     - ./rc-ns.sh
  artifacts:
    paths:
    - output/*
  only:
    - master
