apiVersion: v1
kind: ServiceAccount
metadata:
  name: xopsx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xopsx
spec:
  selector:
    matchLabels:
      app: xopsx
  template:
    metadata:
      labels:
        app: xopsx
    spec:
      serviceAccountName: xopsx
      containers:
      - name: app
        image: harbor-chengdu.nx-engine.com/devops/xopsx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xopsx
subjects:
- kind: ServiceAccount
  name: xopsx
  namespace: default
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
