stages:
  - deploy-env
deploy-to-dev:
  stage: deploy-env
  script:
     - export K8S_KUBECONFIG=${K8S_KUBECONFIG_DEV}
     - export K8S_NS=${K8S_NS_DEV:${K8S_NS}}
     - s2i . deploy
     - deploy-dev-post
  only:
    - master
    - /^rc.*$/
    - /^bugfix.*$/
    - /^hotfix.*$/
    - /^feature.*$/
    - /^dev.*$/
deploy-to-test:
  stage: deploy-env
  when: manual
  script:
    - export SRC_K8S_NS_SUFFIX="-dev"
    - export DST_K8S_NS_SUFFIX="-test"
    - export SRC_KUBE=${K8S_KUBECONFIG_DEV}
    - export DST_KUBE=${K8S_KUBECONFIG_TEST}
    - k8s-app-mirror ${SRC_KUBE} ${DST_KUBE} ${CI_PROJECT_NAME}
    - deploy-test-post
  only:
    - master
    - /^rc.*$/
    - /^bugfix.*$/
    - /^hotfix.*$/
    - /^feature.*$/
    - /^dev.*$/
deploy-to-uat:
  stage: deploy-env
  when: manual
  script:
     - export SRC_K8S_NS_SUFFIX="-test"
     - export DST_K8S_NS_SUFFIX="-uat"
     - export SRC_KUBE=${K8S_KUBECONFIG_TEST}
     - export DST_KUBE=${K8S_KUBECONFIG_UAT}
     - k8s-app-mirror ${SRC_KUBE} ${DST_KUBE} ${CI_PROJECT_NAME}
     - deploy-uat-post
  only:
    - master
    - /^hotfix.*$/
deploy-to-prd:
  stage: deploy-env
  when: manual
  script:
     - export SRC_K8S_NS_SUFFIX="-uat"
     - export DST_K8S_NS_SUFFIX="-prd"
     - export SRC_KUBE=${K8S_KUBECONFIG_UAT}
     - export DST_KUBE=${K8S_KUBECONFIG_PRD}
     - k8s-app-mirror ${SRC_KUBE} ${DST_KUBEG} ${CI_PROJECT_NAME}
     - deploy-prd-post
  only:
    - master
    - /^hotfix.*$/