version: '3'



services:
  logstash:
    restart: always
#    build: .
    image: logstash:6.4.3
    privileged: true
#    command: ["run", "--user=root", "--working-directory=/home/logstash"]
    volumes:
    - ./pipelines.yml:/usr/share/logstash/config/pipelines.yml
    - ./es.conf:/es.conf
