version: '3'
volumes:
  runner-maven-cache: {}
  runner-gitlab-runner-cache: {}
  runner-root-cache: {}
  runner-filebeat-cache: {}
  runner-gitlab-metric-log-cache: {}
  metricbeat-filebeat-cache: {}
services:
  metricbeat:
    restart: always
    #    build: .
    image: harbor.benload.com/bu5/cicd-gitlab-runner-s2e:feature-centos-f12b9b57-1.0.0-g59686-cicd-gitlab-runner-s2e
    #privileged: true
    entrypoint: "/docker/docker-entrypoint-metricbeat.sh"
    env_file:
      - ./metricbeat/secrets/environment-global
    volumes:
      - metricbeat-filebeat-cache:/var/lib/filebeat
      - runner-gitlab-metric-log-cache:/var/log/gitlab-job-metric:ro
      ##########################secrets
      - ./metricbeat/secrets/filebeat/filebeat.yml:/etc/filebeat/filebeat.yml
      - ./metricbeat/secrets/profile.d/env.sh:/etc/profile.d/env.sh
  runner:
    restart: always
    image: harbor.benload.com/bu5/cicd-gitlab-runner-s2e:feature-centos-f12b9b57-1.0.0-g59686-cicd-gitlab-runner-s2e
    privileged: true
    #command: ["github-runner"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-root-cache:/root
      - runner-filebeat-cache:/var/lib/filebeat
      - runner-maven-cache:/root/.m2/repository
      - runner-gitlab-runner-cache:/home/gitlab-runner
      - runner-gitlab-metric-log-cache:/var/log/gitlab-job-metric:rw
      ###########################tools
      - ./runner/tools:/s2e/custom/tools
      ###########################template
      - ./runner/templates:/s2e/custom/templates
      ###########################demo code
      - ./runner/democode:/root/democode
      ###########################secrets
      - ./runner/secrets/android:/etc/android
      - ./runner/secrets/cloud-aliyun:/root/.aliyun
      - ./runner/secrets/cloud-huawei:/root/.huawei
      - ./runner/secrets/cloud-tencent:/root/.tccli
      - ./runner/secrets/docker:/root/.docker
      - ./runner/secrets/email/mail.rc:/etc/mail.rc
      - ./runner/secrets/filebeat/filebeat.yml:/etc/filebeat/filebeat.yml
      - ./runner/secrets/gitlab/.python-gitlab.cfg:/root/.python-gitlab.cfg
      - ./runner/secrets/gitlab-runner/config.toml:/etc/gitlab-runner/config.toml
      - ./runner/secrets/profile.d/env.sh:/etc/profile.d/env.sh
      - ./runner/secrets/jira:/root/jira
      - ./runner/secrets/k8s/.kube:/root/.kube
      - ./runner/secrets/maven/settings.xml:/root/.m2/settings.xml
      - ./runner/secrets/rancher/cli2.json:/root/.rancher/cli2.json
      - ./runner/secrets/s2ectl:/root/.s2ectl