version: '3'
volumes:
  runner-maven-cache: {}
  runner-gitlab-runner-cache: {}
  runner-root-cache: {}
  runner-filebeat-cache: {}
  runner-gitlab-metric-log-cache: {}
services:
  runner:
    restart: always
    image: harbor.benload.com/bu5/cicd-gitlab-runner-s2e:feature-centos-f12b9b57-1.0.0-g59686-cicd-gitlab-runner-s2e
    privileged: true
    #command: ["github-runner"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-root-cache:/root
      - runner-filebeat-cache:/var/lib/filebeat
      - runner-maven-cache:/root/.m2/repository
      - runner-gitlab-runner-cache:/home/gitlab-runner
      - runner-gitlab-metric-log-cache:/var/log/gitlab-job-metric:rw
      ###########################s2e tools &template
      - cicd-s2e-runner/s2e:/s2e
      ###########################demo code
      - ./democode:/root/democode
      ###########################jenkins-agent
      - ./runner/secrets/jenkins-agent:/home/jenkins-agent
      ###########################secrets
