version: '3'
volumes:
  runner-maven-cache: {}
  runner-gitlab-runner-cache: {}
  runner-root-cache: {}
  runner-filebeat-cache: {}
  runner-gitlab-metric-log-cache: {}
  metricbeat-filebeat-cache: {}
services:
  metricbeat:
    restart: always
    #    build: .
    image: harbor.benload.com/bu5/cicd-gitlab-runner-s2e:feature-centos-f12b9b57-1.0.0-g59686-cicd-gitlab-runner-s2e
    #privileged: true
    entrypoint: "/docker/docker-entrypoint-metricbeat.sh"
    env_file:
      - ./metricbeat/secrets/environment-global
    volumes:
      - metricbeat-filebeat-cache:/var/lib/filebeat
      - runner-gitlab-metric-log-cache:/var/log/gitlab-job-metric:ro
      ##########################secrets
      - ./metricbeat/secrets/filebeat/filebeat.yml:/etc/filebeat/filebeat.yml
      - ./metricbeat/secrets/profile.d/env.sh:/etc/profile.d/env.sh
  runner:
    restart: always
    image: harbor.benload.com/bu5/cicd-gitlab-runner-s2e:feature-centos-f12b9b57-1.0.0-g59686-cicd-gitlab-runner-s2e
    privileged: true
    #command: ["github-runner"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-root-cache:/root
      - runner-filebeat-cache:/var/lib/filebeat
      - runner-maven-cache:/root/.m2/repository
      - runner-gitlab-runner-cache:/home/gitlab-runner
      - runner-gitlab-metric-log-cache:/var/log/gitlab-job-metric:rw
      ###########################tools
      - ./runner/tools:/s2e/custom/tools
      ###########################template
      - ./runner/templates:/s2e/custom/templates
      ###########################demo code
      - ./runner/democode:/root/democode
      ###########################secrets
