dependencies:
- name: elasticsearch
  version: ~0.0.1
  repository: "file://charts/elasticsearch"
  condition: elasticsearch.enabled
- name: hbase
  version: ~0.0.1
  repository: "file://charts/hbase"
  condition: hbase.enabled
- name: kafka
  version: ~0.0.1
  repository: "file://charts/kafka"
  condition: kafka.enabled
- name: mongodb
  version: ~0.0.1
  repository: "file://charts/mongodb"
  condition: mongodb.enabled
- name: mysql
  version: ~0.0.1
  repository: "file://charts/mysql"
  condition: mysql.enabled
- name: redis
  version: ~0.0.1
  repository: "file://charts/redis"
  condition: redis.enabled
- name: solr
  version: ~0.0.1
  repository: "file://charts/solr"
  condition: solr.enabled
- name: zookeeper
  version: ~0.0.1
  repository: "file://charts/zookeeper"
  condition: zookeeper.enabled
