{{- if (index .Values (include "xxxxxx.name" .)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "xxxxxx.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    qcloud-app: {{ template "xxxxxx.name" . }}
{{- end }}
