{{- if (index .Values (include "xxxxxx.name" .)) }}
{{- if (index .Values (include "xxxxxx.name" .) "ingress") }}
{{- if (index .Values (include "xxxxxx.name" .) "service") }}
{{- if (index .Values (include "xxxxxx.name" .) "service" "ports") -}}
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  labels:
    qcloud-app: {{ template "xxxxxx.name" . }}
  name: {{ template "xxxxxx.name" . }}-internal
proxy:
  path: /
route:
  strip_path: false
  preserve_host: true
{{- end }}
{{- end }}
{{- end }}
{{- end -}}
