apiVersion: v1
kind: Service
metadata:
  labels:
    app: pinpoint-web
  name: pinpoint-web
spec:
  ports:
  - name: tcp-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: tcp-9997
    port: 9997
    protocol: TCP
    targetPort: 9997
  selector:
    app: pinpoint-web
  type: NodePort