apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinpoint-web
  labels:
    app: pinpoint-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinpoint-web
  template:
    metadata:
      labels:
        app: pinpoint-web
    spec:
      containers:
      - name: pinpoint-web
        image: pinpointdocker/pinpoint-web:1.8.1
        env:
        - name: ADMIN_PASSWORD
          value: admin
        - name: ANALYTICS
          value: "true"
        - name: HBASE_HOST
          value: pinpoint-hbase
        - name: HBASE_PORT
          value: "2181"
        - name: CONFIG_SHOW_APPLICATIONSTAT
          value: "true"
        - name: BATCH_ENABLE
          value: "false"
        - name: JDBC_DRIVER
          value: com.mysql.jdbc.Driver
        - name: JDBC_URL
          value: jdbc:mysql://pinpoint-mysql:3306/pinpoint?characterEncoding=UTF-8
        - name: JDBC_USERNAME
          value: admin
        - name: JDBC_PASSWORD
          value: admin
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 2Gi