apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    description: dddd
  labels: {}
  name: TOBE-REPLACE
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      qcloud-app: TOBE-REPLACE
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels: {}
    spec:
      containers:
      - image: TOBE-REPLACE
        imagePullPolicy: IfNotPresent
        name: TOBE-REPLACE
        volumeMounts:
        - mountPath: /cfg/
          name: TOBE-REPLACE
        resources:
          limits:
            memory: 1536Mi
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 421
          items:
          - key: env.txt
            path: env.txt
          name: TOBE-REPLACE
        name: TOBE-REPLACE
