{{- if (index .Values (include "xxxxxx.name" .)) }}
{{- if (index .Values (include "xxxxxx.name" .) "service") }}
{{- if (index .Values (include "xxxxxx.name" .) "service" "ports") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "xxxxxx.fullname" . }}
  labels:
    qcloud-app: {{ template "xxxxxx.name" . }}
    chart: {{ template "xxxxxx.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
   {{- if and (index .Values (include "xxxxxx.name" .) "service")  (index .Values (include "xxxxxx.name" .) "service" "annotations") }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  {{- if (index .Values (include "xxxxxx.name" .) "service") }}
  {{- if (index .Values (include "xxxxxx.name" .) "service" "type") }}
  type: {{ index .Values (include "xxxxxx.name" .) "service" "type" }}
  {{- else -}}
  type: ClusterIP
  {{- end }}
  {{- end }}
  ports:
  {{- range $port := (index .Values (include "xxxxxx.name" .) "service" "ports")}}
  - name: {{ $port }}-tcp
    port: {{ $port }}
    targetPort: {{ $port }}
    protocol: TCP
  {{- end}}
  selector:
    qcloud-app: {{ template "xxxxxx.name" . }}
  sessionAffinity: None
{{- end }}
{{- end }}
{{- end }}