apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.image | quote }}
        securityContext:
          readOnlyRootFilesystem: true
        readinessProbe:
          tcpSocket:
            port: mongodb
        ports:
        - name: mongodb
          containerPort: 27017
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: mongodb
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: mongodb
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: tmp
        emptyDir:
          medium: Memory
