apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka
    spec:
      hostname: kafka
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:5.1.0
        env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_BROKER_ID
          value: '1'
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: '1'
        ports:
        - name: kafka
          containerPort: 9092
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - 'kafka-broker-api-versions --bootstrap-server kafka:9092'
        volumeMounts:
        - name: kafka
          mountPath: /var/lib/kafka
        - name: log
          mountPath: /var/log/kafka
      volumes:
      - name: kafka
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: kafka
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: log
        emptyDir: {}
