apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  {{- if (index .Values "service") }}
  {{- if (index .Values "service" "type") }}
  type: {{ .Values.service.type }}
  {{- else }}
  type: ClusterIP
  {{- end }}
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app.kubernetes.io/name: redis
