apiVersion: v1
kind: Service
metadata:
  labels:
    app: pinpoint-collector
  name: pinpoint-collector
spec:
  clusterIP: None
  ports:
  - name: tcp-9994
    port: 9994
    protocol: TCP
    targetPort: 9994
  - name: tcp-9995
    port: 9995
    protocol: TCP
    targetPort: 9995
  - name: tcp-9996
    port: 9996
    protocol: TCP
    targetPort: 9996
  - name: udp-9994
    port: 9994
    protocol: UDP
    targetPort: 9994
  - name: udp-9995
    port: 9995
    protocol: UDP
    targetPort: 9995
  - name: udp-9996
    port: 9996
    protocol: UDP
    targetPort: 9996
  selector:
    app: pinpoint-collector
  type: ClusterIP