{{- if (index .Values (include "xxxxxx.name" .)) }}
{{- if (index .Values (include "xxxxxx.name" .) "deployment") }}
{{- if (index .Values (include "xxxxxx.name" .) "deployment" "default") -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "xxxxxx.fullname" . }}
  labels:
    qcloud-app: "{{ template "xxxxxx.name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: app
spec:
  {{- if and (index .Values (include "xxxxxx.name" .)) (index .Values (include "xxxxxx.name" .) "replicaCount") }}
  replicas: {{ index .Values (include "xxxxxx.name" .) "replicaCount" }}
  {{- else }}
  replicas: 1
  {{- end}}
  selector:
    matchLabels:
      qcloud-app: {{ template "xxxxxx.name" . }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        qcloud-app: {{ template "xxxxxx.name" . }}
        release: {{ .Release.Name }}
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: qcloud-app
                      operator: In
                      values:
                        - {{ template "xxxxxx.name" . }}
                topologyKey: kubernetes.io/hostname
      containers:
      - image:   {{ index .Values (include "xxxxxx.name" .) "default-image" }}
        env:
        - name: MY_K8S_NS
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_K8S_SVC_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        imagePullPolicy: IfNotPresent
        name: {{ template "xxxxxx.name" . }}
        {{- if  (index .Values (include "xxxxxx.name" .) "service")  }}
        {{- if  (index .Values (include "xxxxxx.name" .) "service" "ports")  }}
        {{- if (index .Values "global") }}
        {{- if (index .Values "global" "containers") }}
        {{- if (index .Values "global" "containers" "livenessProbe") }}
        livenessProbe:
          failureThreshold: 10
          httpGet:
            httpHeaders:
              - name: User-Agent
                value: s2i-health-check
            path: /actuator/health
            port: {{ first (index .Values (include "xxxxxx.name" .) "service" "ports") }}
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 20
          httpGet:
            httpHeaders:
            - name: User-Agent
              value: s2i-health-check
            path: /actuator/health
            port: {{ first (index .Values (include "xxxxxx.name" .) "service" "ports") }}
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if (.Files.Glob "files/override-entrypoint.sh") }}
        command:
        - /cfg/override-entrypoint.sh
        {{- end}}
        {{- if  (index .Values (include "xxxxxx.name" .) "service")  }}
        {{- if  (index .Values (include "xxxxxx.name" .) "service" "ports")  }}
        ports:
        {{- range $port := (index .Values (include "xxxxxx.name" .) "service" "ports") }}
        - name: {{ $port }}-tcp
          containerPort: {{ $port }}
          protocol: TCP
        {{- end}}
        {{- end}}
        {{- end}}
        resources:
          {{ if  (index .Values (include "xxxxxx.name" .) "resources")  }}
{{ toYaml .Values (include "xxxxxx.name" .) "resources" | indent 10 }}
          {{- else -}}
          limits:
            memory: 2048Mi
          requests:
            cpu: 200m
            memory: 768Mi
          {{- end}}
          {{- if (index .Values "global") }}
          {{- if (index .Values "global" "containers") }}
          {{- if (index .Values "global" "containers" "securityContext") }}
          {{- if (index .Values "global" "containers" "securityContext" "privileged") }}
          securityContext:
            privileged: true
          {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
       {{- if or (.Files.Glob "files/env.txt") (.Files.Glob "files/override-entrypoint.sh") }}
        volumeMounts:
        - mountPath: /cfg/
          name: {{ template "xxxxxx.name" . }}       
       {{- end }}
       {{- if or (.Files.Glob "files/initdata/*")  }}
        - mountPath: /cfg/initdata/
          name: {{ template "xxxxxx.name" . }}-initdata       
       {{- end }}         
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      {{- if or (.Files.Glob "files/env.txt") (and (index .Values (include "xxxxxx.name" .)) (index .Values (include "xxxxxx.name" .) "env.txt")) }}
      volumes:
      - name: {{ template "xxxxxx.name" . }}
        configMap:
          defaultMode: 421
          name: {{ template "xxxxxx.name" . }}
      {{- end}}
      {{- if (.Files.Glob "files/initdata/*") }}
      - name: {{ template "xxxxxx.fullname" . }}-initdata
        configMap:
          defaultMode: 421
          name: {{ template "xxxxxx.fullname" . }}-initdata
      {{- end }}
{{- end }}
{{- end }}
{{- end -}}
