apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: zookeeper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:5.1.0
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: '2181'
        ports:
        - name: zookeeper
          containerPort: 2181
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - '[ "imok" = "$(echo ruok | nc -w 1 localhost 2181)" ]'
        volumeMounts:
        - name: zookeeper
          mountPath: /var/log/zookeeper
        - name: log
          mountPath: /var/log/kafka
      volumes:
      - name: zookeeper
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: zookeeper
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: log
        emptyDir: {}
