apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbase
  labels:
    app.kubernetes.io/name: hbase
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hbase
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hbase
    spec:
      hostname: hbase
      containers:
      - name: hbase
        image: harbor-chengdu.nx-engine.com/library/hbase:1.4.8-phoenix
        readinessProbe:
          exec:
            command: ["sh", "-c", "echo status | /opt/hbase/bin/hbase shell -n"]
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: hbase
          mountPath: /var/lib/hbase
        - name: tmp
          mountPath: /tmp
        resources:
          requests:
            memory: 1Gi
      volumes:
      - name: hbase
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: hbase
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: tmp
        emptyDir:
          medium: Memory
