apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
    spec:
      containers:
      - name: redis
        image: redis:5-alpine
        securityContext:
          readOnlyRootFilesystem: true
        readinessProbe:
          tcpSocket:
            port: redis
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - name: redis
          mountPath: /data
      volumes:
      - name: redis
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: redis
        {{- else }}
        emptyDir: {}
        {{- end }}
