stages:
  - artifact-docker-build
artifact-docker-build:
  stage: artifact-docker-build
  script:
     - git-merge-master
     - s2i . artifact
     - s2i . docker
  except:
    - tags
    - master
  artifacts:
    when: on_success
    expire_in: 24h
    paths:
      - .s2i/
artifact-docker-build-master:
  stage: artifact-docker-build
  script:
     - s2i . artifact
     - s2i . docker
  only:
    - master
    - hotfix/*
  artifacts:
    when: on_success
    name: ${CI_PROJECT_NAME}-${CI_JOB_STAGE}
    expire_in: 24h
    paths:
      - .s2i/