stages:
  - artifact-docker-build
artifact-docker-build:
  stage: artifact-docker-build
  script:
     - s2i . artifact
     - s2i . docker
  only:
    - master
    - /^rc.*$/
    - /^bugfix.*$/
    - /^hotfix.*$/
    - /^feature.*$/ 
  except:
    - /^dev.*$/
