stages:
  - artifact-docker-build
artifact-docker-build:
  stage: artifact-docker-build
  script:
     - git-merge-master
     - s2i . artifact
     - s2i . docker
  except:
    - tags
  artifacts:
    when: on_success
    expire_in: 24h
    paths:
      - .s2i/
