stages:
  - docker-build
docker-build:
  stage: docker-build
  script:
     - s2i . docker-build
  only:
    - master
    - /^rc.*$/
    - /^bugfix.*$/
    - /^hotfix.*$/
    - /^feature.*$/ 
  except:
    - /^dev.*$/
