stages:
  - docker-build
code-analysis:
  stage: docker-build
  script:
     - ./s2e/s2i . docker-build
  only:
    - master
    - /^rc.*$/
    - /^bugfix.*$/
    - /^hotfix.*$/
    - /^feature.*$/ 
  except:
    - /^dev.*$/
