stages:
  - unit-test
unit-test:
  stage: unit-test
  script:
     - echo "TODO"
  only:
    - master
    - /^rc.*$/
    - /^bugfix.*$/
    - /^hotfix.*$/
    - /^feature.*$/ 
  except:
    - /^dev.*$/
