stages:
  - src-release
src-mr-create:
  stage: src-release
  when: manual
  script:
     - gitlab-mr-create
  except:
    - master
    - /^hotfix.*$/
    - tags
stages:
  - src-release
gitlab-auto-merge:
  stage: src-release
  script:
     - gitlab-auto-merge
  only:
    - /^hotfix.*$/
  except:
    - tags