
stages:
  - artifact-release
artifact-release:
  stage: artifact-release
  when: manual
  script:
     - IMG=$(head -n 1 .s2i/s2i.*img.txt)
     - perl -ni -e "s/^image: .+/image: ${IMG}/g;print" runner/docker-compose.yaml
  except:
    - tags
    - master
  artifacts:
    when: on_success
    name: ${CI_PROJECT_NAME}-${CI_JOB_STAGE}
    expire_in: 24h
    paths:
      - runner/