
stages:
  - artifact-release
artifact-release:
  stage: artifact-release
  when: manual
  script:
    - export IMG="$(head -n 1 .s2i/s2i.*img.txt)"
    - export "PERL_EXP=s@image: .+@image: ${IMG}@g;print"
    - perl -ni -e "${PERL_EXP}" runner/docker-compose.yaml
  except:
    - tags
    - master
  artifacts:
    when: on_success
    name: ${CI_PROJECT_NAME}-${CI_JOB_STAGE}
    expire_in: 24h
    paths:
      - runner/