stages:
  - artifact-docker-build
  - deploy-env
  - artifact-release
  - src-release

include:
#  - local: .gitlab/s2i/ci/a0-analysis-code.yml
  - local: .gitlab/s2i/ci/b0-artifact-docker-build.yml
#  - local: .gitlab/s2i/ci/c0-unit-test.yml
  - local: .gitlab/s2i/ci/d0-deploy-env.yml
  - local: .gitlab/s2i/ci/e0-src-release.yml
  - local: .gitlab/s2i/ci/f0-artifact-release.yml