version: '3'


volumes:
  maven-cache: {}
  gitlab-runner-cache: {}
  root-cache: {}


services:
  gitlab-runner:
    restart: always
#    build: .
    image: harbor.nx-engine.com/paas/cicd-gitlab-runner-s2e:feature-centos-0b5759a-cicd-gitlab-runner-s2e-1.0.0-g56631
    privileged: true
#    command: ["run", "--user=root", "--working-directory=/home/gitlab-runner"]
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - root-cache:/root
    - maven-cache:/root/.m2/repository
    - gitlab-runner-cache:/home/gitlab-runner
##########################secrets
    - ./secrets/android:/etc/android
    - ./secrets/cloud-aliyun:/root/.aliyun
    - ./secrets/cloud-huawei:/root/.huawei
    - ./secrets/cloud-tencent:/root/.tccli
    - ./secrets/docker:/root/.docker
    - ./secrets/email/mail.rc:/etc/mail.rc
    - ./secrets/filebeat/filebeat.yml:/etc/filebeat/filebeat.yml
    - ./secrets/gitlab/.python-gitlab.cfg:/root/.python-gitlab.cfg
    - ./secrets/gitlab-runner/config.toml:/etc/gitlab-runner/config.toml
    - ./secrets/gitlab-runner/profile.d/env.sh:/etc/profile.d/env.sh
    - ./secrets/jira:/root/jira
    - ./secrets/k8s/.kube:/root/.kube
    - ./secrets/maven/settings.xml:/root/.m2/settings.xml
    - ./secrets/s2ectl:/root/.s2ectl
###########################tools
    - ./tools:/s2e/custom/tools
###########################template
    - ./templates:/s2e/custom/templates




