stages:
  - s2
s2:
  stage: s2
  script:
     - echo s2
     - echo VAR="${VAR}"
     - export VAR="${VAR} s2"
  only:
    - master
    - /^rc.*$/
    - /^bugfix.*$/
    - /^hotfix.*$/
    - /^feature.*$/ 
  except:
    - /^dev.*$/