name: ci-lab

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - release*
      - master*
      - feature*

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  DOCKER_REPO: registry-1.docker.io
  DOCKER_NS: bettercode
  DOCKER_PASS: '${{ secrets.HUB_DOCKER_COM_PASS }}'
  GITHUB_TOKEN: '${{ secrets.HUB_TOKEN }}'

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build-xxxx:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build, Push image
        run: |
          set +e
          env
          which -a go
          go get github.com/github-release/github-release
          which github-release

