apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinpoint-hbase
  labels:
    app: pinpoint-hbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinpoint-hbase
  template:
    metadata:
      labels:
        app: pinpoint-hbase
    spec:
      hostname: pinpoint-hbase
      containers:
      - name: pinpoint-hbase
        image: pinpointdocker/pinpoint-hbase:1.8.1
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 1Gi