apiVersion: v1
kind: Service
metadata:
  labels:
    app: pinpoint-hbase
  name: pinpoint-hbase
spec:
  clusterIP: None
  ports:
  - name: tcp-2181
    port: 2181
    protocol: TCP
    targetPort: 2181
  - name: tcp-16010
    port: 16010
    protocol: TCP
    targetPort: 16010
  - name: tcp-16030
    port: 16030
    protocol: TCP
    targetPort: 16030
  - name: tcp-60000
    port: 60000
    protocol: TCP
    targetPort: 60000
  - name: tcp-60020
    port: 60020
    protocol: TCP
    targetPort: 60020
  selector:
    app: pinpoint-hbase
  type: ClusterIP